export enum BUTTON_VARIANT {
	PRIMARY_HIGHLIGHTED_ROUNDED = 'primary-highlighted-rounded',
	PRIMARY_ELEVATED_ROUNDED = 'primary-elevated-rounded',
	PRIMARY_BORDER_ROUNDED = 'primary-bordered-rounded',
	PRIMARY_TRANSPARENT = 'primary-transparent',
	SECONDARY_HIGHLIGHTED_ROUNDED = 'secondary-highlighted-rounded',
	SECONDARY_ELEVATED_ROUNDED = 'secondary-elevated-rounded',
	SECONDARY_BORDER_ROUNDED = 'secondary-bordered-rounded',
	SECONDARY_TRANSPARENT = 'secondary-transparent',
	ACCENT_HIGHLIGHTED_ROUNDED = 'accent-highlighted-rounded',
	ACCENT_ELEVATED_ROUNDED = 'accent-elevated-rounded',
	ACCENT_BORDER_ROUNDED = 'accent-bordered-rounded',
	ACCENT_TRANSPARENT = 'accent-transparent',
	DANGER_HIGHLIGHTED_ROUNDED = 'danger-highlighted-rounded',
	DANGER_ELEVATED_ROUNDED = 'danger-elevated-rounded',
	DANGER_BORDER_ROUNDED = 'danger-bordered-rounded',
	DANGER_TRANSPARENT = 'danger-transparent',
}

export enum BUTTON_CLASSES {
	BASE = 'btn',
	ELEVATED_ROUNDED = 'elevated-rounded',
	BORDER_ROUNDED = 'bordered-rounded',
	TRANSPARENT = 'transparent',
	HIGHLIGHTED_ROUNDED = 'highlighted-rounded',
	PRIMARY = 'primary-btn',
	SECONDARY = 'secondary-btn',
	ACCENT = 'accent-btn',
	DANGER = 'danger-btn',
}

export enum BUTTON_LABELS {
  SIGN_IN = 'Sign In',
  SIGN_UP = 'Sign Up For Free',
  REGISTER = 'Register',
  LOGIN = 'Login',
  LOGOUT = 'Logout',
  POST = 'Post',
  COMMENT = 'Comment',
  UPDATE = 'Update',
  CHANGE = 'Change',
  DELETE = 'Delete',
  VIEW_POST = 'View Full Post',
  FOLLOW = 'Follow',
  UNFOLLOW = 'Unfollow',
}